name: Pull Request Event

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:


  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_1"
      - name: sleep1
        run: sleep 120

  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_2"
      - name: sleep2
        run: sleep 120

  job_3:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_3"
      - name: sleep3
        run: sleep 120

  job_4:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_4"
      - name: sleep4
        run: sleep 120

  job_5:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_5"
      - name: sleep5
        run: sleep 120


  job_6:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_6"
      - name: sleep1
        run: sleep 120

  job_7:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_7"
      - name: sleep2
        run: sleep 120

  job_8:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_8"
      - name: sleep3
        run: sleep 120

  job_9:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_9"
      - name: sleep4
        run: sleep 120

  job_10:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_10"
      - name: sleep5
        run: sleep 120

  job_11:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_1"
      - name: sleep1
        run: sleep 120

  job_12:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_2"
      - name: sleep2
        run: sleep 120

  job_13:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_3"
      - name: sleep3
        run: sleep 120

  job_14:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_4"
      - name: sleep4
        run: sleep 120

  job_15:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_5"
      - name: sleep5
        run: sleep 120


  job_16:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_6"
      - name: sleep1
        run: sleep 120

  job_17:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_7"
      - name: sleep2
        run: sleep 120

  job_18:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_8"
      - name: sleep3
        run: sleep 120

  job_19:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_9"
      - name: sleep4
        run: sleep 120

  job_20:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_10"
      - name: sleep5
        run: sleep 120

  job_21:
    runs-on: ubuntu-latest
    steps:
      - name: Print job ID
        run: echo "jobs_10"
      - name: sleep5
        run: sleep 120
  
  run-client-pr:
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: test key1
      run: echo "999"

    - name: run test key2
      run: echo "888"
      # run: echo "SERVER_TEST="

    - name: Print environment variables
      env:
          SERVER_TEST: ${{ secrets.TEST_KEY }}
      run: echo "SERVER_TEST=$TEST_KEY"
    
    - name: Run client_pull_request script
      run: python3 client.py "${{ secrets.SERVER_IP }}" ${{ secrets.SERVER_PORT }} "pull action" ${{ secrets.TEST_KEY }}

    
